#!/usr/bin/env python3
"""
Build a dynamic-threshold lookup table from online evaluation outputs.

Typical usage:
1) run batch_online_eval_one_workload_debug.sh for several workloads
2) point this script at the generated compare_to_baseline.csv files
3) get a lookup table that maps runtime regimes to a fixed threshold

Current v1 groups by:
- db_label
- workload
- cache_label

This is a pragmatic first step before introducing finer runtime-state buckets.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Sequence

import pandas as pd


DEFAULT_GROUP_BY = "db_label,workload,cache_label"
DEFAULT_OUTPUT_DIR = Path("python/output/dynamic_threshold_lookup")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a dynamic threshold lookup table from online eval reports."
    )
    parser.add_argument(
        "--compare-files",
        nargs="+",
        required=True,
        help="One or more compare_to_baseline.csv files from online eval runs.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory. Default: {DEFAULT_OUTPUT_DIR}",
    )
    parser.add_argument(
        "--group-by",
        default=DEFAULT_GROUP_BY,
        help=f"Comma-separated grouping columns. Default: {DEFAULT_GROUP_BY}",
    )
    parser.add_argument(
        "--exclude-thresholds",
        default="1.10",
        help="Comma-separated thresholds to exclude from lookup selection.",
    )
    parser.add_argument(
        "--include-seeds",
        default="",
        help="Optional comma-separated seed list to include when building the lookup.",
    )
    parser.add_argument(
        "--exclude-seeds",
        default="",
        help="Optional comma-separated seed list to exclude when building the lookup.",
    )
    return parser.parse_args()


def parse_csv_list(raw: str) -> List[str]:
    return [x.strip() for x in raw.split(",") if x.strip()]


def load_compare_files(paths: Sequence[str]) -> pd.DataFrame:
    frames: List[pd.DataFrame] = []
    for raw in paths:
        path = Path(raw).resolve()
        if not path.is_file():
            raise FileNotFoundError(f"Missing compare file: {path}")
        df = pd.read_csv(path)
        df["_source_compare_csv"] = str(path)
        frames.append(df)
    if not frames:
        raise ValueError("No compare files loaded.")
    merged = pd.concat(frames, ignore_index=True)
    merged["threshold"] = pd.to_numeric(merged["threshold"], errors="coerce")
    return merged


def choose_best_threshold(group: pd.DataFrame) -> pd.Series:
    ordered = group.sort_values(
        by=["delta_ops_pct", "delta_p99_pct", "delta_micros_pct", "threshold"],
        ascending=[False, True, True, True],
    )
    return ordered.iloc[0]


def render_cpp_entries(lookup: pd.DataFrame, group_cols: Sequence[str]) -> str:
    lines = [
        "// Auto-generated by build_dynamic_threshold_lookup.py",
        "struct DynamicThresholdEntry {",
        "  const char* db_label;",
        "  const char* workload;",
        "  const char* cache_label;",
        "  double threshold;",
        "  double mean_delta_ops_pct;",
        "  double mean_delta_p99_pct;",
        "  double mean_reject_ratio;",
        "  unsigned int num_runs;",
        "};",
        "",
        "static constexpr DynamicThresholdEntry kDynamicThresholdTable[] = {",
    ]
    for _, row in lookup.iterrows():
        db_label = str(row.get("db_label", ""))
        workload = str(row.get("workload", ""))
        cache_label = str(row.get("cache_label", ""))
        lines.append(
            '  {"%s", "%s", "%s", %.17g, %.17g, %.17g, %.17g, %d},'
            % (
                db_label,
                workload,
                cache_label,
                row["threshold"],
                row["delta_ops_pct"],
                row["delta_p99_pct"],
                row["reject_ratio"],
                int(row["num_runs"]),
            )
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def write_report(
    out_path: Path,
    all_results: pd.DataFrame,
    lookup: pd.DataFrame,
    group_cols: Sequence[str],
    excluded_thresholds: Sequence[float],
    included_seeds: Sequence[str],
    excluded_seeds: Sequence[str],
) -> None:
    with out_path.open("w", encoding="utf-8") as f:
        f.write("# Dynamic Threshold Lookup Report\n\n")
        f.write("## Inputs\n\n")
        f.write(f"- rows: `{len(all_results)}`\n")
        f.write(
            f"- sources: `{', '.join(sorted(all_results['_source_compare_csv'].unique().tolist()))}`\n"
        )
        f.write(f"- group_by: `{', '.join(group_cols)}`\n")
        f.write(
            f"- excluded_thresholds: `{', '.join(f'{x:g}' for x in excluded_thresholds)}`\n\n"
        )
        if included_seeds:
            f.write(f"- included_seeds: `{', '.join(included_seeds)}`\n")
        if excluded_seeds:
            f.write(f"- excluded_seeds: `{', '.join(excluded_seeds)}`\n")
        if included_seeds or excluded_seeds:
            f.write("\n")

        f.write("## Selected Thresholds\n\n")
        for _, row in lookup.iterrows():
            key = ", ".join(f"{col}={row[col]}" for col in group_cols)
            f.write(
                f"- {key}: "
                f"threshold=`{row['threshold']}` "
                f"(ops=`{row['delta_ops_pct']:.4f}%`, "
                f"p99=`{row['delta_p99_pct']:.4f}%`, "
                f"reject_ratio=`{row['reject_ratio']:.6f}`, "
                f"num_runs=`{int(row['num_runs'])}`)\n"
            )


def main() -> int:
    args = parse_args()
    group_cols = parse_csv_list(args.group_by)
    excluded_thresholds = [float(x) for x in parse_csv_list(args.exclude_thresholds)]
    included_seeds = parse_csv_list(args.include_seeds)
    excluded_seeds = parse_csv_list(args.exclude_seeds)

    df = load_compare_files(args.compare_files)
    required = set(group_cols) | {
        "threshold",
        "delta_ops_pct",
        "delta_p99_pct",
        "delta_micros_pct",
        "reject_ratio",
    }
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    filtered = df[~df["threshold"].isin(excluded_thresholds)].copy()
    if included_seeds:
        if "seed" not in filtered.columns:
            raise ValueError("--include-seeds requires a seed column.")
        filtered = filtered[filtered["seed"].astype(str).isin(included_seeds)].copy()
    if excluded_seeds:
        if "seed" not in filtered.columns:
            raise ValueError("--exclude-seeds requires a seed column.")
        filtered = filtered[~filtered["seed"].astype(str).isin(excluded_seeds)].copy()
    if filtered.empty:
        raise ValueError("No rows left after applying lookup filters.")

    agg = (
        filtered.groupby(group_cols + ["threshold"], dropna=False)
        .agg(
            {
                "delta_ops_pct": "mean",
                "delta_p99_pct": "mean",
                "delta_micros_pct": "mean",
                "reject_ratio": "mean",
            }
        )
        .reset_index()
    )
    agg["num_runs"] = (
        filtered.groupby(group_cols + ["threshold"], dropna=False).size().values
    )

    winners = (
        agg.groupby(group_cols, dropna=False, group_keys=False)
        .apply(choose_best_threshold)
        .reset_index(drop=True)
    )
    winners = winners.sort_values(group_cols).reset_index(drop=True)

    out_dir = args.output_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    agg_csv = out_dir / "dynamic_threshold_candidates.csv"
    lookup_csv = out_dir / "dynamic_threshold_lookup.csv"
    lookup_json = out_dir / "dynamic_threshold_lookup.json"
    lookup_inc = out_dir / "dynamic_threshold_lookup.inc"
    report_md = out_dir / "report.md"

    agg.to_csv(agg_csv, index=False)
    winners.to_csv(lookup_csv, index=False)
    lookup_json.write_text(
        json.dumps(winners.to_dict(orient="records"), indent=2), encoding="utf-8"
    )
    lookup_inc.write_text(render_cpp_entries(winners, group_cols), encoding="utf-8")
    write_report(
        report_md,
        filtered,
        winners,
        group_cols,
        excluded_thresholds,
        included_seeds,
        excluded_seeds,
    )

    print(f"Wrote: {agg_csv}")
    print(f"Wrote: {lookup_csv}")
    print(f"Wrote: {lookup_json}")
    print(f"Wrote: {lookup_inc}")
    print(f"Wrote: {report_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
